// Per-track accent color. The first four slots keep the established palette
// (cyan / purple / orange / green) for visual continuity with the pre-pool UI;
// the rest are generated by rotating the hue wheel so every one of the 32 pool
// slots gets a distinct, stable color.
const BASE_COLORS = ['#00f0ff', '#c084fc', '#fb923c', '#4ade80'] as const;

export function trackColor(index: number): string {
  if (index < BASE_COLORS.length) return BASE_COLORS[index];
  // Golden-angle hue rotation gives well-separated hues without a lookup table.
  const hue = Math.round((index * 137.508) % 360);
  return `hsl(${hue}, 80%, 65%)`;
}
